### PR TITLE
Feature routing

### PR DESCRIPTION
**Pull request by gulsher7**

### CODE REVIEW

**Comment by ajakka** [comment]
Hi @gulsher7, thanks for your contribution. 
I have reviewed your code, and you did a great job 👍🏼 

However, I get two errors on the `animateToRoute` function (see attached image)
I fixed them by changing the animation declaration to this:

```swift
let animation: MapCameraAnimation = MapCameraAnimationFactory.createAnimation(
            from: update,
            duration: TimeInterval(1),
            easingFunction: EasingFunction.inCubic)
```

Please change it on your side and let me know if it works.
another thing is that I want you to format the code using the shortcut ctrl*i on xcode, just to have a unified formatting of the code :)

And as we discussed, I'll work on the Android side and publish a new version soon.

Thank you for your time and efforts :)

image

**Comment by ajakka** [comment]
@gulsher7 and about your concern for the performance implications of calling `updateFeature` on every `didSet` of the Routing component. I also agree that it could affect the performance, but not calling it Makes the Routing component not respond to changes on the JS side. on android there is a function called `onAfterUpdateTransaction` that I use to wait until all the props are updated then call updateFeature, but I'm not sure if there's a similar function on iOS

**Comment by gulsher7** [comment]
> Hi @gulsher7, thanks for your contribution. I have reviewed your code, and you did a great job 👍🏼
> 
> However, I get two errors on the `animateToRoute` function (see attached image) I fixed them by changing the animation declaration to this:
> 
> ```swift
> let animation: MapCameraAnimation = MapCameraAnimationFactory.createAnimation(
>             from: update,
>             duration: TimeInterval(1),
>             easingFunction: EasingFunction.inCubic)
> ```
> 
> Please change it on your side and let me know if it works. another thing is that I want you to format the code using the shortcut ctrl*i on xcode, just to have a unified formatting of the code :)
> 
> And as we discussed, I'll work on the Android side and publish a new version soon.
> 
> Thank you for your time and efforts :)
> 
> image

Hey, i'm not getting this error at my side, could yo please verify the here map sdk version i'm using 4.18.1.0.103798-release version

**Comment by ajakka** [comment]
I'm using HERE navigate version 4.18.2.0.105808-release:
`sdk version==>> SDKVersion(productVariant: "explore", versionName: "4.18.2.0.105808-release", versionGeneration: 4, versionMajor: 18, versionMinor: 2, versionPatch: 0, versionBuild: 105808, versionTag: "release", backendConfig: "PRD")`

**Comment by gulsher7** [comment]
Screenshot 2024-05-12 at 10 15 01 PM

I guess the error above is due to a version mismatch. If I use the code you provided, it gives me a deprecated warning

**Comment by gulsher7** [comment]
i'm using explore sdk

**Comment by ajakka** [comment]
Yes, your right. I cleared the Pod file and re-instantiated it, and it now works.

**Pull request merged**
